### ISSUE TITLE
Bad practice to return string from WSGI application.

### ISSUE THREAD

**Issue by GrahamDumpleton** [PerimeterX/perimeterx-python-wsgi#1]
The WSGI specification says you should return an iterable. In line:

* https://github.com/PerimeterX/perimeterx-python-wsgi/blob/master/perimeterx/middleware.py#L104

you are doing that, the problem is you have:

```
return str(body)
```

This means you are returning a string.

The WSGI specification means that a WSGI server is supposed to interpret that as an iterable over a sequence of strings where each string is one character.

because a WSGI server is required to flush each item yielded from the sequence, this will be very inefficient. You should use:

```
return [str(body)]
```

Even then, this still looks suspicious that you are using ``str()``. This will fail under Python 3 as it results in it returning a Unicode string and not a byte string.

Whatever is returned for each item by the iterable must be a byte string. On Python this means you should encode to a byte string with appropriate encoding and ensure you are setting the appropriate header in the response to indicate the encoding type.

**Comment by bendpx** [comment]
Thank you Graham, you are right. 

This issue is now resolved and published: v1.0.2
