### ISSUE TITLE
PerimeterX.verify() should always return a pair

### ISSUE THREAD

**Issue by kevinhb** [PerimeterX/perimeterx-python-wsgi#59]
https://github.com/PerimeterX/perimeterx-python-wsgi/blob/18f0a8302d51d985cf4e0e860791f69fd7466af3/perimeterx/middleware.py#L80

This function always returns a pair unless it encounters an exception in the `try` block, in which case it always just returns `True`.  This is guaranteed to throw its own exception in the unpacking assignment where `verify()` is called on L47 (`TypeError: 'bool' object is not iterable`).

**Comment by ilaipx** [comment]
Fixed by #60
